language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer install --no-interaction
  - composer self-update
  - php artisan key:generate

script:
  - vendor/bin/phpunit